// <auto-generated />
using System;
using EFCoreModelApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreModelApp.Migrations
{
    [DbContext(typeof(HRDbContext))]
    partial class HRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("EFCoreModelApp.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Human Resources",
                            Location = "New York"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "IT",
                            Location = "San Francisco"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Finance",
                            Location = "Chicago"
                        });
                });

            modelBuilder.Entity("EFCoreModelApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentID = 1,
                            FirstName = "Jorge",
                            LastName = "Colewall"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentID = 2,
                            FirstName = "Anna",
                            LastName = "Smith"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentID = 2,
                            FirstName = "Peter",
                            LastName = "Brown"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentID = 3,
                            FirstName = "Liam",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("EFCoreModelApp.Models.Employee", b =>
                {
                    b.HasOne("EFCoreModelApp.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCoreModelApp.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
